# Generated by Django 3.1 on 2020-08-21 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_ordersingleproduct_order_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billingaddress',
            name='same_billing_address',
        ),
    ]
